import type { AppProps } from "next/app";

import Head from "next/head";
import { Toaster } from "react-hot-toast";

import Layout from "@/components/layouts/Layout";

import { jakartaSans, poppins } from "@/styles/fonts";

import "@/styles/globals.css";
import "tailwindcss/tailwind.css";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<style jsx global>
				{`
					html {
						--poppins-font: ${poppins.style.fontFamily};
						--jakartaSans-font: ${jakartaSans.style.fontFamily};
					}
				`}
			</style>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Toaster
					position="top-center"
					toastOptions={{
						duration: 3000,
						style: {
							marginBottom: " 3px",
							width: "100%",
							height: "50px",
							maxWidth: "450px",
							borderRadius: "10px",
						},
						success: {
							style: {
								background: "#63d246",
								color: "#fff",
							},
							iconTheme: {
								primary: "#fff",
								secondary: "#63d246",
							},
						},
						error: {
							style: {
								background: "#ff4c4d",
								color: "#fff",
							},
							iconTheme: {
								primary: "#fff",
								secondary: "#ff4c4d",
							},
						},
					}}
				/>
				<Component {...pageProps} />
			</Layout>
		</>
	);
}
