import type { AppProps } from "next/app";

import Head from "next/head";
import Layout from "@/components/layouts/Layout";

import { jakartaSans, poppins } from "@/styles/fonts";

import "@/styles/globals.css";
import "tailwindcss/tailwind.css";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<style jsx global>
				{`
					html {
						--poppins-font: ${poppins.style.fontFamily};
						--jakartaSans-font: ${jakartaSans.style.fontFamily};
					}
				`}
			</style>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</>
	);
}
