import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="text-red-700 text-lg">
					Lorem Ipsum is simply dummy text of the printing and typesetting
					industry.
				</div>
				<div className="font-jakarta  text-lg">
					Lorem Ipsum is simply dummy text of the printing and typesetting
					industry.
				</div>
			</main>
		</>
	);
}
